import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"], weight : ['400' , '500' ,'600' , '700']
});

const ovo = Ovo({
  subsets: ["latin"], weight : ['400']
});

export const metadata = {
  title: "Portfolio - yeasin munshi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${outfit.className} ${ovo.className} antialiased leading-8 overflow-x-hidden`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
